# Application Port Setting
server:
  port: 8084

spring:
  # Enable Live Reload
  devtools:
    livereload:
      enabled: true

# cors 설정
cors:
  allowed-origins: 'https://whatsports.site'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

---

aws:
  dynamodb:
    endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
    accessKey: AKIAYWWWZSBOLGYF7RRA
    secretKey: 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
  region: ap-northeast-2