package com.firstbusan.wkos.review.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.firstbusan.wkos.dynamodb.LocalDateConverter;
import lombok.*;

import java.time.LocalDateTime;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@DynamoDBTable(tableName = "wkos")
public class ReviewEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "tableName-facilityId-index", attributeName = "tableName")
    @DynamoDBAttribute
    private String tableName;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "tableName-facilityId-index", attributeName = "facilityId")
    @DynamoDBAttribute
    private Integer facilityId;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private Integer score;

    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDateTime date;
}